# -*- restclient -*-
#
# Queries against the /xandar/tags endpoints
#

# variables
:date := (shell-command-to-string "echo -n (date +%Y-%m-%d-%M-%s)")
:host = 127.0.0.1:8001
:path = xandar/tags
:json = application/json

#
# Get a single tags object
#
GET http://:host/:path/58bc450d5984183817000001

#
# Get all tags
#
GET http://:host/:path?per_page=15

#
# Get all tags for a user
#
GET http://:host/:path?where=(userId eq 56d7cc3fccee17506699e735)

#
# Create a tags object for one user
#
POST http://:host/:path
Content-Type: :json
{
  "userId": "56d7cc3fccee17506699e735",
  "tags": ["programming","must-read","haskell","javascript"]
}

#
# Update the tags for a user
#
PUT http://:host/:path/58bc450d5984183817000001
Content-Type: :json
{
  "userId": "56d7cc3fccee17506699e735",
  "tags": ["programming","must-read","go","technology","design","web"]
}

#
# Create multiple tags objects
#
POST http://:host/:path
Content-Type: :json
[{
  "userId": "54c31312bef9f6ce5fc1f23d",
  "tags": ["web-design","sql","mongodb"]
},{
  "userId": "56da18c8fa51ced05cd8db0a",
  "tags": ["technology","security","cryptography"]
}]