# -*- restclient -*-
#
# Queries against the /xandar/post-queries endpoints
#

# variables
:date := (shell-command-to-string "echo -n (date +%Y-%m-%d-%M-%s)")
:host = 127.0.0.1:8001
:path = xandar/post-queries
:json = application/json

#
# Get a single post query
#
GET http://:host/:path/58bb873a5984183970000003

#
# Get all post queries
#
GET http://:host/:path?per_page=15

#
# Find post queries
#
GET http://:host/:path?where=(userText contains 'read')

#
# Create a single post-query
#
POST http://:host/:path
Content-Type: :json
{
  "userId": "56d7cc3fccee17506699e735",
  "pinState": 0,
  "title": "Posts containing monad topics",
  "userText": "\"monad cofunctor\" & :unread",
  "text": "(\"monad cofunctor\" & :unread)",
  "query": "(read eq false) and (post.title contains 'monad cofunctor' or post.description:2 contains 'monad cofunctor')",
  "lastUsed": "2017-03-05T03:32:24.903Z"
}