# -*- restclient -*-
#
# Queries against the /xandar/posts endpoints
#

# variables
:date := (shell-command-to-string "echo -n (date +%Y-%m-%d-%M-%s)")
:host = 127.0.0.1:8001
:path = xandar/posts
:json = application/json

#
# Get all posts
#
GET http://:host/:path?per_page=2

#
# Get all posts - sort & partial response
#
GET http://:host/:path?sort=image.url&include=title,link,image

#
# Get all posts for feed 1
#
GET http://:host/:path?where=(feedId eq '56d7de0dc788cb1d6eb91abb')&include=title,feedId,link

#
# Get all posts for feed 2
#
GET http://:host/:path?where=(feedId eq 56d7de0dc788cb1d6eb91abb)&include=title,feedId,link

#
# Count posts for feed
#
HEAD http://:host/:path?where=(feedId eq 56d7defcc788cb1d6eb922c8)&include=title,feedId,link

#
# Count posts for feed 2
#
HEAD http://:host/:path?where=(feedId eq 56d7df24c788cb1d6eb92486)&include=title,feedId,link

#
# Count posts for feed 3
#
HEAD http://:host/:path?where=(feedId eq 56d7e122c788cb1d6eb93495)&include=title,feedId,link

#
# Get multiple posts by id
#
GET http://:host/:path?where=(_id in ['56d7de0dc788cb1d6eb91abc', '56d7de0dc788cb1d6eb91abd', '56d7de0dc788cb1d6eb91abe'])&include=title,feedId,link

#
# Get all posts for feeds
#
GET http://:host/:path?where=(feedId in ['56d7defcc788cb1d6eb922c8', '56d7de07c788cb1d6eb91a6d', '56d7ddf8c788cb1d6eb919d8', '56d7e029c788cb1d6eb92c65'])&include=title,feedId,link

#
# Get posts filtered by status
#
GET http://:host/:path?where=(title contains "taking")&include=title,link

#
# Get posts created afte a date
#
GET http://:host/:path?where=(createdAt ge 2017-01-08T07:47:45.928Z)

#
# Get all posts - pagination
#
GET http://:host/:path?page=4&per_page=5

#
# Get a single post
# feedId: 56d7d88bc788cb1d6eb9199c
#
GET http://:host/:path/56d7d88bc788cb1d6eb9199d

#
# Get a single post using ETag
#
GET http://:host/:path/5869ec3e59841810dc000009
If-None-Match: ef19b2e0ce2baa83fa90abfa82a5141d4f18842d

#
# Delete a non-existent post
#
DELETE http://:host/:path/non-existent

#
# Delete an existent post
#
DELETE http://:host/:path/587ad5bd5984186b15000001

#
# Create a single post
#
POST http://:host/:path
Content-Type: :json
{
  "author": "Bill Wadman & Jeffery Saddoris",
  "comments": null,
  "date": "2016-03-01T18:30:00.000Z",
  "description": "post content",
  "feedId": "56d7d88bc788cb1d6eb9199c",
  "guid": "http://5by5.tv/otp/205",
  "image": {
    "url": "http://icebox.5by5.tv/images/broadcasts/48/cover.jpg"
  },
  "link": "http://5by5.tv/otp/205",
  "pubdate": "2016-03-01T18:30:00.000Z",
  "summary": "post summary",
  "title": "On Taking Pictures 201: No Such Thing as Never or Always"
}

#
# Create multiple posts
#
POST http://:host/:path
Content-Type: :json
[
  {
    "author": "Adam Dachis & Darren Herczeg",
    "comments": null,
    "date": "2016-03-03T00:15:00.000Z",
    "description": "post description",
    "feedId": "56d7d88bc788cb1d6eb9199c",
    "guid": "http://5by5.tv/supercharged/97",
    "image": {
      "url": "http://icebox.5by5.tv/images/broadcasts/69/cover.jpg"
    },
    "link": "http://5by5.tv/supercharged/97",
    "pubdate": "2016-03-03T00:15:00.000Z",
    "summary": "post summary",
    "title": "Supercharged 97: Nothing Happened This Week"
  },
  {
    "author": "Darryl Thomas",
    "comments": null,
    "date": "2016-03-02T16:00:00.000Z",
    "description": "post description",
    "feedId": "56d7d88bc788cb1d6eb9199c",
    "guid": "http://5by5.tv/iohyes/103",
    "image": {
      "url": "http://icebox.5by5.tv/images/broadcasts/77/cover.jpg"
    },
    "link": "http://5by5.tv/iohyes/103",
    "pubdate": "2016-03-02T16:00:00.000Z",
    "summary": "post summary",
    "title": "iOhYes 103: Don\"t Hate Us, Nolan"
  }
]

#
# Replace a single post
#
PUT http://:host/:path/587a810d598418739b000001
Content-Type: :json
{
    "email": "replaced3@aol.com",
    "admin": true
}

#
# Modify a single post
#
PATCH http://:host/:path/587ad83859841886c7000003
Content-Type: :json
{
    "email": "updated3@aol.com"
}
